# Generated by Django 4.2.30 on 2026-06-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='student_slug',
            field=models.SlugField(default='daniea', unique=True),
            preserve_default=False,
        ),
    ]
