# Generated by Django 4.2.30 on 2026-06-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='student_slug',
            field=models.SlugField(default='daniea'),
            preserve_default=False,
        ),
    ]
