# Generated by Django 4.2.30 on 2026-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('professional', 'Professional')], default='technical', max_length=20)),
                ('proficiency', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
